spring.application.name=learning_management_system
# postgres config
spring.datasource.url=jdbc:postgresql://localhost:5432/lms_db
spring.datasource.username=m.pourbafrani
spring.datasource.password=m.pourbafrani
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configuration (optional, but commonly used)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# or create, create-drop, none
spring.jpa.hibernate.ddl-auto=update
# show SQL queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT configuration
jwt.secret=jsf8n3hA7JpKzQxLmT9vY2rUjnKJEqw09cX5aW8bE
# 1 hour in milliseconds
jwt.expiration=3600000
# 7 days in milliseconds
jwt.refreshExpiration=604800000

# redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
