spring.application.name=learning_management_system
# postgres config
spring.datasource.url=jdbc:postgresql://172.17.0.2:5432/lms_db
spring.datasource.username=m.pourbafrani
spring.datasource.password=m.pourbafrani
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configuration (optional, but commonly used)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update # or create, create-drop, none
spring.jpa.show-sql=true # show SQL queries in console
spring.jpa.properties.hibernate.format_sql=true
